import Head from 'next/head'
import Link from 'next/link'
import React, { useContext, useEffect, useState } from 'react'
import { Store } from '../utils/Store'
import { BsCart2 } from "react-icons/bs";

export default function Layout({title, children}) {
    
    const {state, dispatch} = useContext(Store)
    const {cart} = state
    const [cartItemsCount, setCartItemsCart] = useState(0)

    useEffect(() => {
        setCartItemsCart(cart.cartItems.reduce((a, c)=>a + c.quantity, 0))
    }, [cart.cartItems])
 
    return (
    <div>
        <Head>
        <title>{title ? title + " - shopping" : "shopping"}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className="navbar navbar-expand-lg navbar-dark bg-dark">
         <div className="container">
                    <Link href="/" className="navbar-brand" >
                        Shopping
                    </Link>
                    {/* <button className="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                        <span className="navbar-toggler-icon"></span>
                    </button> */}
                <div id="navbarNav">
                    <ul className="navbar-nav ms-auto ">
                        <li className="nav-item">    
                            <Link href="/Cart" className="nav-link active" style={{display:'flex', alignItems: 'center'}}>
                                <BsCart2/> <span className='text-white rounded p-1' >{cartItemsCount}</span>
                            </Link>
                        </li>
                        {/* <li className="nav-item">
                            <Link href="/" className="nav-link" >
                                Features
                            </Link>
                        </li>
                        <li className="nav-item">
                            <Link href="/" className="nav-link" >
                                Pricing
                            </Link>
                        </li> */}
                    </ul>
                </div>
        </div>
      </nav>
      <main>
        {children}
      </main>





    </div>
  )
}
