const data = {
    products: [
      {
        name: "Shirt LA",
        slug: "shirt-la",
        category: "Shirts",
        image: "/images/ShirtLa.jpg",
        price: 100,
        rating: 4.9,
        countInStock: 25,
        description: "A popular shirt",
      },
      {
        name: "Shirt NY",
        slug: "ny-shirt",
        category: "Shirts",
        image: "/images/shirtNY.jpg",
        price: 100,
        rating: 4.8,
        countInStock: 20,
        description: "A popular shirt",
      },
      {
        name: "Jean Mom Men",
        slug: "jean-mom",
        category: "Pants",
        image: "/images/jean-mom-men.jpg",
        price: 100,
        rating: 4.8,
        countInStock: 10,
        description: "A popular Jean",
      },
      {
        name: "Jogger Mom",
        slug: "jogger-mom",
        category: "Pants",
        image: "/images/jogger-mom-mens.jpg",
        price: 105,
        rating: 4.9,
        countInStock: 15,
        description: "A popular Jogger",
      },
      {
        name: "Jean Mom Women",
        slug: "jeanMom",
        category: "Pants",
        image: "/images/jean-momWomen.jpg",
        price: 100,
        rating: 4.5,
        countInStock: 13,
        description: "A popular Jean",
      },
      {
        name: "Jean Mom Pink",
        slug: "jeanMomPink",
        category: "Pants",
        image: "/images/jean-mom-women.jpg",
        price: 89,
        rating: 4.2,
        countInStock: 5,
        description: "A popular Jean",
      },
      {
        name: "White Shirt",
        slug: "free-shirt",
        category: "Shirts",
        image: "/images/shirt1.jpg",
        price: 70,
        rating: 4.5,
        countInStock: 20,
        description: "A popular shirt",
      },
      {
        name: "Fit Shirt",
        slug: "fit-shirt",
        category: "Shirts",
        image: "/images/shirt2.jpg",
        price: 80,
        rating: 3.2,
        countInStock: 0,
        description: "A popular shirt",
      },
      {
        name: "Black T Shirt",
        slug: "black t-shirt",
        category: "Shirts",
        image: "/images/blackShirt.png",
        price: 90,
        rating: 4.2,
        countInStock: 10,
        description: "A popular shirt",
      },
      {
        name: "Black Swim Shorts",
        slug: "black-swim-shorts",
        category: "Shorts",
        image: "/images/black-short.jpg",
        price: 70,
        rating: 9,
        countInStock: 10,
        description: "A popular short",
      },
      {
        name: "Flowered Swim Shorts",
        slug: "flowered-swim-shorts",
        category: "Shorts",
        image: "/images/floweredSwimShort.jpg",
        price: 75,
        rating: 3,
        countInStock: 10,
        description: "A popular short",
      },
      {
        name: "Bikini",
        slug: "bikini",
        category: "Bikini",
        image: "/images/bikini.jfif",
        price: 55,
        rating: 4.1,
        countInStock: 6,
        description: "A popular bikini",
      },
      {
        name: "Slim Shirt",
        slug: "slim-shirt",
        category: "Shirts",
        image: "/images/shirt3.jpg",
        price: 90,
        rating: 4.5,
        countInStock: 20,
        description: "A popular shirt",
      },
      {
        name: "Jeans Pants",
        slug: "jean-pants",
        category: "Pants",
        image: "/images/pants1.jpg",
        price: 90,
  
        rating: 2.9,
  
        countInStock: 20,
        description: "Smart looking pants",
      },
      {
        name: "Fit Pants",
        slug: "fit-pants",
        category: "Pants",
        image: "/images/pants2.jpg",
        price: 95,
        rating: 3.5,
        countInStock: 20,
        description: "A popular pants",
      },
      {
        name: "Classic Pants",
        slug: "classic-pants",
        category: "Pants",
        image: "/images/pants3.jpg",
        price: 75,
        rating: 2.4,
        countInStock: 20,
        description: "A popular pants",
      },
    ],
  };
  
  export default data